spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6psy:mysql://rm-bp162pgo0uzr9u0hcmo.mysql.rds.aliyuncs.com:3306/exblog?serverTimezone=Asia/Shanghai
    username: zlc01
    password: ZLC@@@111

  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/